### ISSUE TITLE
Create tables to support application data

### ISSUE THREAD

**Issue by kramsey458** [M3NACK/meat-meets-meat#1]
Gimme da tables. Caroline said she would take care of this

**Comment by carolinecullen** [comment]
DONE: Here are the create statements.


CREATE TABLE avatar (
	aid INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80)
);

CREATE TABLE users (
	username VARCHAR(80) NOT NULL,
	password VARCHAR(80) NOT NULL,
	first VARCHAR(80) NOT NULL,
	last VARCHAR(80) NOT NULL,
	aid INTEGER,
	UNIQUE (username),
	PRIMARY KEY (username),
	FOREIGN KEY (aid) REFERENCES avatar(aid)
);

CREATE TABLE beers (
	bid INTEGER AUTO_INCREMENT PRIMARY KEY,
	brewery VARCHAR(80),
	brewname VARCHAR(80) NOT NULL
);

CREATE TABLE beer_choices (
	bcid INTEGER AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(80),
	bid INTEGER,
	FOREIGN KEY (bid) REFERENCES beers(bid),
	FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE matches (
	mid INTEGER AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(80),
	matched_user VARCHAR(80),
	bid INTEGER,
	FOREIGN KEY (bid) REFERENCES beers(bid),
	FOREIGN KEY (username) REFERENCES users(username),
	FOREIGN KEY (matched_user) REFERENCES users(username)
);

**Comment by adrenick** [comment]
@carolinecullen I like you and the things you do - Secretly Jully
